apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-fitness-application
  namespace: acme-fitness
spec:
  project: default

  source:
    repoURL: https://github.com/Jocasmen94/acme-fitness.git
    targetRevision: HEAD
    path: kubernetes-manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: acme-fitness

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      